### ISSUE TITLE
Error getting OMP_NUM_THREADS

### ISSUE THREAD

**Issue by josephmje** [BIDS-Apps/HCPPipelines#40]
Hi,

I've been trying to run HCPPipelines in a singularity container but I get the following error:

```
Traceback (most recent call last):
  File "/run.py", line 347, in <module>
    stage_func()
  File "/run.py", line 71, in run_pre_freesurfer
    run(cmd, cwd=args["path"], env={"OMP_NUM_THREADS": str(args["n_cpus"])})
  File "/run.py", line 30, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1
```

This is my singularity call:
`singularity run -H ${tmp_dir} -B ${bids_dir}:/bids -B ${output_dir}:/out ${sing_container} /bids /out participant --participant_label UT1UT10006 --license_key="*CYjRpyK" --n_cpus 3`

I've also tried not including `--n_cpus` in my singularity call, leaving the default, and still get the same error.

**Comment by DavidEWarrenPhD** [comment]
Was this resolved?  I'm seeing a similar error in the PostFreeSurfer stage:

```
terminate called after throwing an instance of 'RBD_COMMON::BaseException'

/opt/HCP-Pipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh: line 205:  1150 Aborted                 (core dumped) ${MSMBINDIR}/msm --conf=${MSMCONFIGDIR}/MSMSulcStrainFinalconf --inmesh="$AtlasSpaceFolder"/"$NativeFolder"/${Subject}.${Hemisphere}.sphere.rot.native.surf.gii --refmesh="$AtlasSpaceFolder"/"$Subject"."$Hemisphere".sphere."$HighResMesh"k_fs_LR.surf.gii --indata="$AtlasSpaceFolder"/"$NativeFolder"/${Subject}.${Hemisphere}.sulc.native.shape.gii --refdata="$AtlasSpaceFolder"/${Subject}.${Hemisphere}.refsulc."$HighResMesh"k_fs_LR.shape.gii --out="$AtlasSpaceFolder"/"$NativeFolder"/MSMSulc/${Hemisphere}. --verbose


Traceback (most recent call last):
  File "/run.py", line 349, in <module>
    stage_func()
  File "/run.py", line 114, in run_post_freesurfer
    run(cmd, cwd=args["path"], env={"OMP_NUM_THREADS": str(args["n_cpus"])})
  File "/run.py", line 30, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 134
```

I'm getting this error with both the latest release and dev build docker images.

**Comment by josephmje** [comment]
The container might need to be either built or run with the `--privileged` flag. That seemed to fix the issue for me.

**Comment by DavidEWarrenPhD** [comment]
OK — running with `--privileged` didn't help in my case.  I'll raise a new issue.
