### ISSUE TITLE
Error in PostFreeSurfer stage

### ISSUE THREAD

**Issue by DavidEWarrenPhD** [BIDS-Apps/HCPPipelines#41]
I'm getting the following error at the PostFreeSurfer stage after apparently successful PreFreeSurfer and FreeSurfer stages:

```
terminate called after throwing an instance of 'RBD_COMMON::BaseException'

/opt/HCP-Pipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh: line 205:  1150 Aborted                 (core dumped) ${MSMBINDIR}/msm --conf=${MSMCONFIGDIR}/MSMSulcStrainFinalconf --inmesh="$AtlasSpaceFolder"/"$NativeFolder"/${Subject}.${Hemisphere}.sphere.rot.native.surf.gii --refmesh="$AtlasSpaceFolder"/"$Subject"."$Hemisphere".sphere."$HighResMesh"k_fs_LR.surf.gii --indata="$AtlasSpaceFolder"/"$NativeFolder"/${Subject}.${Hemisphere}.sulc.native.shape.gii --refdata="$AtlasSpaceFolder"/${Subject}.${Hemisphere}.refsulc."$HighResMesh"k_fs_LR.shape.gii --out="$AtlasSpaceFolder"/"$NativeFolder"/MSMSulc/${Hemisphere}. --verbose


Traceback (most recent call last):
  File "/run.py", line 349, in <module>
    stage_func()
  File "/run.py", line 114, in run_post_freesurfer
    run(cmd, cwd=args["path"], env={"OMP_NUM_THREADS": str(args["n_cpus"])})
  File "/run.py", line 30, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 134
```

The error occurs with both the latest release version and the dev version.  The call is:

```
docker run -ti --rm -v /mnt/clinical/PrismaQC/2018_12_07/bids:/bids_dir:ro -v ~/Temp/hcpp_output:/output_dir 415ddb225c5b bids_dir output_dir participant --participant_label qc31 --stages PostFreeSurfer --license_key FAKEKEY
```

Adding `--privileged` and/or calling with `sudo` did not change the result.  Setting the `OMP_NUM_THREADS` environment variable explicitly for the docker run call did not change the result.

**Comment by DavidEWarrenPhD** [comment]
I'm going to close — although this issue is observed when using Docker on lab workstations, we're not seeing it when calling the app through Singularity on the local cluster (where most processing will happen).
